version: "3"
services:

  discoveryservice:
    image: bilalannavi/discoveryservice
    ports:
      - "8761:8761"
    networks:
      - backend
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  userservice:
    image: bilalannavi/userservice
    ports:
      - "8010:8010"
    networks:
      - backend
    depends_on:
      - discoveryservice
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  apigateway:
    image: bilalannavi/apigateway
    ports:
      - "8081:8081"
    networks:
      - backend
    depends_on:
      - discoveryservice
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  
networks:
  backend:

