version: "3.9"
services:

  discoveryservice:
    image: discoveryservice
    ports:
      - "8761:8761"
    networks:
      - backend
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  userservice:
    image: userservice
    ports:
      - "5000"
    networks:
      - backend
    depends_on:
      - discoveryservice
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  apigateway:
    image: apigateway
    ports:
      - "8081:8081"
    networks:
      - backend
    depends_on:
      - discoveryservice
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  
networks:
  backend:

