apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert --out kompose_generated
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.network/backend: "true"
    io.kompose.service: apigateway
  name: apigateway
spec:
  containers:
    - image: bilalannavi/apigateway
      name: apigateway
      ports:
        - containerPort: 8081
      resources: {}
  restartPolicy: OnFailure
status: {}
