apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert --out kompose_generated
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.network/backend: "true"
    io.kompose.service: discoveryservice
  name: discoveryservice
spec:
  containers:
    - image: bilalannavi/discoveryservice
      name: discoveryservice
      ports:
        - containerPort: 8761
      resources: {}
  restartPolicy: OnFailure
status: {}
