apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert --out kompose_generated
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.network/backend: "true"
    io.kompose.service: userservice
  name: userservice
spec:
  containers:
    - image: bilalannavi/userservice
      name: userservice
      ports:
        - containerPort: 8010
      resources: {}
  restartPolicy: OnFailure
status: {}
